buildvariants:
- display_name: Ubuntu 18.04
  name: ubuntu1804
  run_on:
  - ubuntu1804-small
  tasks:
  - name: unit_tests
  - name: deploy
  - name: documentation
  - name: evg_api_install
  - name: check_pypi_version

functions:
  create virtualenv:
  - command: shell.exec
    params:
      working_dir: src
      script: |
        set -o errexit
        set -o verbose

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        /opt/mongodbtoolchain/v3/bin/python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip

        export PIPX_HOME="$HOME/pipx"
        export PIPX_BIN_DIR="$HOME/pipx/bin"
        export PATH="$PATH:$PIPX_BIN_DIR"

        rm -rf "$PIPX_HOME"

        pip install --disable-pip-version-check --quiet pipx==1.1.0
        pipx install poetry==1.2.0 --force
        poetry install

  deploy:
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -o errexit
          . venv/bin/activate

          if [ "${is_patch}" = "true" ]; then
            # Do not deploy on patches.
            exit 0
          fi

          export PATH="$PATH:$HOME/pipx/bin"
          poetry publish --build --username ${pypi_user} --password ${pypi_password}

  build_docs:
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -o errexit
          set -o verbose
          . venv/bin/activate

          export PATH="$PATH:$HOME/pipx/bin"
          poetry run sphinx-apidoc -o docs/source src "*cli*"
          poetry run sphinx-build -W docs/source docs/build
          git clean -d -f

  publish_docs:
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -o errexit
          set -o verbose
          . venv/bin/activate

          if [ "${is_patch}" = "true" ]; then
            # Do not deploy on patches.
            exit 0
          fi

          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          export PATH="$PATH:$HOME/pipx/bin"
          poetry run gh-pusher --build-dir docs/build

  check_version_update:
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -o errexit
          set -o verbose

          wget -q https://github.com/dbradf/pypi-version-check/releases/download/v0.3.0/pypi-version-check
          chmod +x pypi-version-check

          ./pypi-version-check

pre:
- command: git.get_project
  params:
    directory: src
- func: create virtualenv

post:
- command: attach.xunit_results
  params:
    file: src/junit-*.xml

tasks:
- name: unit_tests
  commands:
  - command: shell.exec
    params:
      working_dir: src
      script: |
        set -o errexit
        set -o verbose

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        . venv/bin/activate

        export PATH="$PATH:$HOME/pipx/bin"
        RUN_SLOW_TESTS=1 poetry run pytest --cov=src --junitxml=junit-test-output.xml

- name: evg_api_install
  commands:
  - command: shell.exec
    params:
      working_dir: src
      script: |
        set -o errexit
        set -o verbose

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        /opt/mongodbtoolchain/v3/bin/python3 -m venv evg-api-cli-venv
        . evg-api-cli-venv/bin/activate

        pip install --upgrade pip
        pip install .

        evg-api --help

- name: check_pypi_version
  commands:
  - func: check_version_update

- name: deploy
  patchable: false
  depends_on:
    - name: unit_tests
    - name: check_pypi_version
  commands:
    - func: deploy

- name: documentation
  depends_on:
    - name: unit_tests
  commands:
    - func: build_docs
    - func: publish_docs
