buildvariants:
- display_name: Ubuntu 16.04
  name: ubuntu1604
  run_on:
  - ubuntu1604-test
  tasks:
  - name: unit_tests
  - name: deploy

functions:
  create virtualenv:
  - command: shell.exec
    params:
      working_dir: src
      script: |
        set -o errexit
        set -o verbose

        /opt/mongodbtoolchain/v3/bin/python3 -m venv venv
        . venv/bin/activate
        pip install poetry
        poetry install

  deploy:
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -o errexit
          . venv/bin/activate

          if [ "${is_patch}" = "true" ]; then
            # Do not deploy on patches.
            exit 0
          fi

          poetry publish --username ${pypi_user} --password ${pypi_password}

pre:
- command: git.get_project
  params:
    directory: src
- func: create virtualenv

post:
- command: attach.xunit_results
  params:
    file: src/junit-*.xml

tasks:
- name: unit_tests
  commands:
  - command: shell.exec
    params:
      working_dir: src
      script: |
        set -o errexit
        set -o verbose

        . venv/bin/activate

        RUN_SLOW_TESTS=1 poetry run pytest --junitxml=junit-test-output.xml

- name: deploy
  patchable: false
  depends_on:
    - name: unit_tests
  commands:
    - func: deploy