name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build API docs
      uses: ammaraskar/sphinx-action@5.3.0
      with:
        build-command: sphinx-apidoc -o docs/source src "*cli*"
    - name: Build HTML
      uses: ammaraskar/sphinx-action@5.3.0
      with:
        build-command: sphinx-build -W docs/source docs/build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
